### ISSUE TITLE
pDesktopManagerInternal is null

### ISSUE THREAD

**Issue by c0ffeeartc** [Ciantic/VirtualDesktopAccessor#10]
Latest version won't work.
TestVirtualDesktopAccessorWin32.exe writes `FATAL ERROR: pDesktopManagerInternal is null` and stops working

**Comment by joshglendenning** [comment]
Are you also on the anniversary update? I'm having this issue too and I'm wondering if the update broke the dll.

**Comment by joshglendenning** [comment]
Looks like we just need to update the MIDL_INTERFACE GUID (https://github.com/verth/virtualdesktops/commit/f26de80950e1f09213b1a7f35a7699ce44a9e5d6).

I'll submit a pull request soon.

**Comment by Ciantic** [comment]
You must have been using old version with Anniversary Update.

I've updated the DLL to use right GUID (F31574D6-B682-4CDC-BD56-1827860ABEC6) before it was released. You need to download the new dll.

**Comment by joshglendenning** [comment]
Ah, I noticed it was updated when I was looking through the source. I'll give it another shot on Tuesday when I'm back at work.

**Comment by c0ffeeartc** [comment]
I wasn't on anniversary update. After updating windows all works
