### ISSUE TITLE
 "regdb_e_classnotreg class not registered" after call CoCreateInstance, pServiceProvider still null pointer

### ISSUE THREAD

**Issue by jih836** [Ciantic/VirtualDesktopAccessor#12]
Hi~ 
I have a problem when my MFC program load VirtualDesktopAccessor.dll always exception appeared, 
I try to trace VirtualDesktopAccessor.dll soure code, that issue about access violation occurred from "_RegisterService" function and get error code is "regdb_e_classnotreg class not registered" after call CoCreateInstance, pServiceProvider still null pointer, but my develop OS & SDK has up to Windows 10 already, I have something wrong?

**Comment by Ciantic** [comment]
I don't know, I do know that with old Windows 10 build (before anniversary edition) it causes null errors. This version supports only the latest Windows 10 (The anniversary edition). You have to get older from revision history if you need older dll.

**Comment by sdias** [comment]
Yes, Jari is right. Thanks.

Basically the version of the DLL you need to use depends on the version of
your Windows. The patches on older releases include an older version of the
DLL that you can try, if your Windows is not up-to-date.

**Comment by jih836** [comment]
Thanks Jari, Sergio reply & sharing,
I check Microsoft anniversary edition number is 1607, and using 3 PC (Windows 10) to verify VirtualDesktopAccessor, all PC up to date  anniversary edition, but only 1 PC occur null errors on all PC (I using this PC to coding) other 2 PC using VirtualDesktopAccessor to working normally.
Except OS envirnmental any causes are there unregistered some COM service possibility? thanks

**Comment by sdias** [comment]
Sorry, please ignore my previous reply, I thought this issue had been
raised in my own repo.
