### ISSUE TITLE
Wrong parameter in script example

### ISSUE THREAD

**Issue by char101** [Ciantic/VirtualDesktopAccessor#14]
```autohotkey
OnExplorerRestart(wParam, lParam, msg, hwnd) {
    global RestartVirtualDesktopAccessorProc
    DllCall(RestartVirtualDesktopAccessorProc, UInt, result)
}
```

`result` is undefined and unnecessary I think since the function return value is `void`.

**Comment by GitKDF** [comment]
Also I feel like:
	DllCall(MoveWindowToDesktopNumberProc, UInt, activeHwnd, UInt, number)
	DllCall(GoToDesktopNumberProc, UInt, number)

should be:
	if DllCall(MoveWindowToDesktopNumberProc, UInt, activeHwnd, UInt, number)
	{
		DllCall(GoToDesktopNumberProc, UInt, number)
	}

to only move if the window was moved.  For example: calling that hotkey with focus on the desktop.

**Comment by Ciantic** [comment]
Yes, the script is more of an example I haven't kept up to date. I currently have other ways to e.g. move windows between desktops, like switch desktop while dragging a window.

**Comment by j4hangir** [comment]
This procedure is not working anymore, does it?

**Comment by Porco-Rosso** [comment]
> Yes, the script is more of an example I haven't kept up to date. I currently have other ways to e.g. move windows between desktops, like switch desktop while dragging a window.

Could you share how you accomplish this? I have been looking how to do exactly that.

~~I can't seem to get your example script working.~~
I'm on windows LTSB and got it working with the "releases version". Still interested in drag+switch

**Comment by Ciantic** [comment]
@Porco-Rosso you just look that when switching desktops if the Left mouse button is held down, if it is you move the active window with you, something like this:

```
; Switching desktops:
; Win + Ctrl + 1 = Switch to desktop 1
*#1::MoveOrGotoDesktopNumber(0)

; Win + Ctrl + 2 = Switch to desktop 2
*#2::MoveOrGotoDesktopNumber(1)

MoveOrGotoDesktopNumber(num) {
    ; If user is holding down Mouse left button, move the current window also
    if (GetKeyState("LButton")) {
        MoveCurrentWindowToDesktop(num)
    } else {
        GoToDesktopNumber(num)
    }
    return
}
```
