### ISSUE TITLE
Not working with Windows 1703 update

### ISSUE THREAD

**Issue by VarunAgw** [Ciantic/VirtualDesktopAccessor#15]
:(

**Comment by Ciantic** [comment]
Open the system Information, what it says on the version?

I'm running Version	10.0.15063 Build 15063 which is supposed to be Creators Update and it seems to be working

**Comment by Ciantic** [comment]
This dialog, please open it and show the number:

![image](https://cloud.githubusercontent.com/assets/64731/24880118/d41d41b6-1e41-11e7-8137-8429d307029d.png)

**Comment by Ciantic** [comment]
Or open the System modern app:

![image](https://cloud.githubusercontent.com/assets/64731/24880344/bccb53c6-1e42-11e7-8dd3-58152c6f977a.png)

**Comment by mzomparelli** [comment]
@VarunAgw If it doesn't work now then give me more info and a few hours. I'll need you to perform some steps on your PC. You'll need access to the registry using the registry editor.

Once open, search for a string (CTRL+F) and type this without quotes "IVirtualDesktopManagerInternal".

If it finds something then please post a screen shot of the window.

**Comment by VarunAgw** [comment]
My OS build is 15063.0. I installed it fresh from windows iso.

**Comment by Ciantic** [comment]
@VarunAgw interesting, how does it fail? It seems to work just fine on my computer but I did the upgrade instead fresh installation.

**Comment by VarunAgw** [comment]
It's weird. I don't know what happened. I redownloaded latest dll from github. It is working now :/

**Comment by Ciantic** [comment]
Oh great, thanks.

**Comment by VarunAgw** [comment]
Sorry I bothered you earlier :(

**Comment by Ciantic** [comment]
No problem.
