### ISSUE TITLE
I created some simple python 2.7 bindings

### ISSUE THREAD

**Issue by reckoner** [Ciantic/VirtualDesktopAccessor#17]
Here is the repository:

https://github.com/reckoner/pyVirtualDesktopAccessor

**Comment by Ciantic** [comment]
Great, maybe it will help someone. 

Word of a caution though, the DLL must be updated. This DLL uses a hidden COM interface (it's private), and goes broken rather often. I have just recently updated the DLL for 1809 (not backwards compatible with older Windows versions).
