### ISSUE TITLE
Moving windows does not work in the latest 1809 update windows build

### ISSUE THREAD

**Issue by shiro** [Ciantic/VirtualDesktopAccessor#21]
Thank you a lot for creating this, it saved me a great deal of pain and made my windows experience bearable over the past year.

I just installed win10 education edition `version 1809 build 17763.316` and it seems like the `MoveWindowToDesktopNumber` function is not doing anything at all.

Have been heavily relying on my script for a long time, so it definitely works (I have also been using it on the win10 education edition, so it's probably not related).

I singled out the function call in a dummy script and it indeed does not work. I'm not completely sure about the other functions right now, will test further.

My AHK code is very similar to the example in the docs.

Help is greatly appreciated since I cannot use windows without my script, getting annoyed constantly.
Thanks!

**edit**
As far as my testing goes `IsWindowOnCurrentVirtualDesktop` also does not seem to work, which completely breaks my script apparently.

Just moving between desktops works.

**Comment by Ciantic** [comment]
You use word "also" there, are both broken for you, or just the `IsWindowOnCurrentVirtualDesktop`?

**Comment by Ciantic** [comment]
It works for me, I added also a test for that function. If you are a programmer you can try the test like this:

1. Open the solution in Visual Studio 

2. Start a Notepad 

3. Start the debug project (by default TestVirtualDesktopAccessorWin32) e.g. from the menu by Debug -> Start Debugging.

The test moves the notepad between current and next (+1) desktop, so make sure you have at least one more desktop from the desktop you started the test.

The output you see should look something like this: 

```
Desktops: 14
Console Window's Desktop Number: 2
Current Desktop Number: 2
Is notepad on this desktop: 1
Is notepad on current desktop: 1
Try pinning the notepad (the window).
Is notepad pinned?1
Is notepad pinned?0
Try pinning the notepad (the app executable).
Is notepad pinned app?1
Is notepad pinned app?0
Notepad is on on the current desktop.
Notepad should now have been moved to the next desktop.
Current Desktop GUID: {5F693E2A-AF18-4ACF-86E2-CBEFA84E8033}
Console Window's Desktop GUID: {5F693E2A-AF18-4ACF-86E2-CBEFA84E8033}
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 2 new:3
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 3 new:2
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 2 new:3
CurrentVirtualDesktopChanged old: 3 new:2
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 0 new:0
CurrentVirtualDesktopChanged old: 0 new:0
```

**Comment by shiro** [comment]
Seems like I had an older version, thank you **so** much!
Everything's working like a charm again and I can use windows once more 👍 .

*Side note: do you have suggestions how to fix the windows icon flashing behaviour in the taskbar (app focus) after desktop switch? Flashes quite often for me*
