### ISSUE TITLE
VWMess is not called

### ISSUE THREAD

**Issue by Trismegistos84** [Ciantic/VirtualDesktopAccessor#22]
On desktop switch function VWMess(wParam, lParam, msg, hwnd) is not called. As a result of that after desktop switch window is not focused.

**Comment by Ciantic** [comment]
Works for me. Are you running on OS build 17763.348? And using this DLL: https://github.com/Ciantic/VirtualDesktopAccessor/raw/master/x64/Release/VirtualDesktopAccessor.dll 

I know that Windows is having a patch tuesday, and I think I haven't yet downloaded that.
