### ISSUE TITLE
Which Ctrl?

### ISSUE THREAD

**Issue by shaynez** [Ciantic/VirtualDesktopAccessor#23]
Currently, both Ctrl could be used to switch to the next desktop, how can I limit it to only work for right or left ctrl? Thanks.

**Comment by Ciantic** [comment]
This is a DLL, it does not bind keyboard shortcuts. You bind shortcuts with own AutoHotkey script.

I'm closing this issue, but feel free to ask more questions, maybe your issue is with autohotkey script of yours.
