### ISSUE TITLE
IsWindowOnCurrentVirtualDesktop does not work in Windows 1809 April 2019

### ISSUE THREAD

**Issue by char101** [Ciantic/VirtualDesktopAccessor#24]
OS Build 17763.475

VirtualDesktopAccessor has been update to the latest version

```
> git log -n5
commit a7aa8715d49fd48d66cb235f5217937a05743d49 (HEAD -> master, origin/master, origin/HEAD)
Author: Jari Pennanen <ciantic@oksidi.com>
Date:   Tue Feb 26 00:15:04 2019 +0200

    ...

commit 6f3755ea56fa177d81db24e3c7cd845a2c2b0a60
Author: Jari Pennanen <ciantic@oksidi.com>
Date:   Fri Oct 5 22:19:57 2018 +0300

    further fixes for 1809 (these are not major flaws though)
```

Test script

```autohotkey
#NoEnv

SetTitleMatchMode 2

hVirtualDesktopAccessor := DllCall("LoadLibrary", Str, A_ScriptDir . "\x64\Release\VirtualDesktopAccessor.dll", "Ptr")

global IsWindowOnCurrentVirtualDesktopProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "IsWindowOnCurrentVirtualDesktop", "Ptr")

IsWindowOnCurrentVirtualDesktop(windowID:=0) {
	return DllCall(IsWindowOnCurrentVirtualDesktopProc, windowID) == 1
}

Run Notepad
Sleep 100
hwnd := WinExist("Notepad")
if (IsWindowOnCurrentVirtualDesktop(hwnd)) {
	MsgBox found: %hwnd%
} else {
	MsgBox not found: %hwnd%
}
```

Result

![notepad](https://user-images.githubusercontent.com/71255/57526295-3df00580-7357-11e9-932f-6819c6eb3232.png)

The result of `IsWindowOnCurrentVirtualDesktopProc` is empty (string?) by the way.

**Comment by Ciantic** [comment]
It works for me, you have to try it with the Visual Studio project and start Notepad. Then hit Launch.

**Comment by Ciantic** [comment]
See these lines: 

https://github.com/Ciantic/VirtualDesktopAccessor/blob/master/TestVirtualDesktopAccessorWin32/TestVirtualDesktopAccessorWin32.cpp#L94-L95

They give me result 1: 

![image](https://user-images.githubusercontent.com/64731/57533413-628fb180-7346-11e9-9b50-487a459115f5.png)

**Comment by Ciantic** [comment]
@char101 Your script is broken, this works:

```

hVirtualDesktopAccessor := DllCall("LoadLibrary", Str, A_ScriptDir . "\x64\Release\VirtualDesktopAccessor.dll", "Ptr")

IsWindowOnCurrentVirtualDesktopProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "IsWindowOnCurrentVirtualDesktop", "Ptr")

Run Notepad
Sleep 1000
hwnd := WinExist("ahk_class Notepad")
MsgBox, %IsWindowOnCurrentVirtualDesktopProc%
MsgBox, %hwnd%
bloo := DllCall(IsWindowOnCurrentVirtualDesktopProc, UInt, hwnd, UInt)
MsgBox, %bloo%
```

**Comment by char101** [comment]
Thanks, the problem was that I was using `DetectHiddenWindows On` and while searching for the windows of an executable, it detects the hidden window as being in the current desktop and tried to activate it. I suspected that the problem was in `IsWindowOnCurrentVirtualDesktopProc` because I just upgraded to 1809 and there was no problem when runing 1803.

**Comment by Ciantic** [comment]
@char101 nope, your script has several problems, for starters it never finds the HWND of a notepad:

```

Run Notepad
Sleep 100
hwnd := WinExist("Notepad")
MsgBox, %hwnd%
```

Is simply wrong, it produces always 0x0 which is not a handle to notepad:

![image](https://user-images.githubusercontent.com/64731/57574060-ab289700-743a-11e9-92a3-517372296ab4.png)

Second, your script is using call `DllCall(IsWindowOnCurrentVirtualDesktopProc, windowID)` which is also totally incorrect to my knowledge, it should be something like `DllCall(IsWindowOnCurrentVirtualDesktopProc, UInt, hwnd, Int)`

**Comment by char101** [comment]
Thanks but I already fixed my script by adding `DetectHiddenWindows On`.

Also, `WinExist("Notepad")` works if you add `SetTitleMatchMode 2`.
