### ISSUE TITLE
+#2::MoveCurrentWindowToDesktop(1) doesn't work in Win10 1803

### ISSUE THREAD

**Issue by Setaran** [Ciantic/VirtualDesktopAccessor#25]
I'm using AHK script example, and I only changed this:
hVirtualDesktopAccessor := DllCall("LoadLibrary", Str, "C:\Users\S\Pictures\VirtualDesktopAccessor.dll", "Ptr") 
Juts correct location for the dll.
And the hotkey to move window to another virtual desktop doesn't work.
I'm on Win10 1803 and I don't want to upgrade to 1809. 
Thanks :)

**Comment by Ciantic** [comment]
You have to get older DLL from the history.
