### ISSUE TITLE
Any issues with 1903 build?

### ISSUE THREAD

**Issue by suskozaver** [Ciantic/VirtualDesktopAccessor#26]
Anyone knows?

**Comment by Carnbroe** [comment]
Only been using it for a few days now but so far no issues

**Comment by suskozaver** [comment]
I got the 1903 yesterday, haven't seen anything yet also.

Thx!

**Comment by Ciantic** [comment]
I don't know yet. I haven't gotten 1903, I get to test that version of windows maybe at the end of month.

**Comment by Ciantic** [comment]
Seems to be working.
