### ISSUE TITLE
Moving window does not work in version 1903

### ISSUE THREAD

**Issue by mschz** [Ciantic/VirtualDesktopAccessor#27]
Hi,
I read (https://github.com/sdias/win-10-virtual-desktop-enhancer/issues/131 and https://github.com/Ciantic/VirtualDesktopAccessor/issues/21) that the latest version of the DLL should resolve the problem that moving a windows doesn't work with newer builds of Windows 10. I just installed Windows 10, Version 1903 (OS Build 18362.175) and found there problem is back again. I downloaded win-10-virtual-desktop-enhancer, changed "MoveWindowToDesktop" to "Win, Alt", downloaded your latest DLL and replaced Windows.10.Virtual.Desktop.Enhancer.0.11.2/libraries/virtual-desktop-accessor.dll with your DLL. Generally win-10-virtual-desktop-enhancer works fine, but moving windows doesn't work.
Did I miss anything?
Michael.

**Comment by Ciantic** [comment]
Yeah, you missed something. I'm running: 1903 (OS Build 18362.239), moving windows between desktops works just fine. Make sure you have downloaded the latests one from the repo: https://github.com/Ciantic/VirtualDesktopAccessor/raw/master/x64/Release/VirtualDesktopAccessor.dll

(Not the releases part, I haven't updated that)

I have also tested this with the older .175 you seem to have)
