### ISSUE TITLE
Cannot make it work in 1903

### ISSUE THREAD

**Issue by stanstrup** [Ciantic/VirtualDesktopAccessor#28]
Hello,

I have been trying to run the script from here: https://superuser.com/questions/1408214/make-programs-specifically-chrome-open-on-same-virtual-desktop/1484958#answer-1477582

It works on one of my computer that has Windows version 1803 and OS build 17134.1069 if I use the 6f3755ea56fa177d81db24e3c7cd845a2c2b0a60 version of the script. But not with the latest version.

On another computer I have version 1903, OS build 18362.418 and was not able to make the script work.

Any hints or something needs an upgrade?

Best,
Jan.

**Comment by Ciantic** [comment]
It works with 1903 (18362.418) I use that (I haven't yet tested with 1909 though).

Ensure you have downloaded the DLL from the repo (NOT the releases tab):

https://github.com/Ciantic/VirtualDesktopAccessor/blob/master/x64/Release/VirtualDesktopAccessor.dll

**Comment by stanstrup** [comment]
Hmpf. I had done exactly that. I thought. Re-downloaded and tried again. Now it works... :(

Thanks.

**Comment by stanstrup** [comment]
Ok this is weird. Now it doesn't work again.
The variables are empty.

```
Global Variables (alphabetical)
--------------------------------------------------
0[1 of 3]: 0
A_Args: Object object {address: 0x9C4790}
AStr[0 of 0]:  
EnumAddress[8 of 63]: 10989792
ErrorLevel[1 of 3]: 0
file: File object {address: 0xA79840}
FILENAME[48 of 63]: C:\Users\tmh331\Desktop\fix_windows\possaves.txt
hVirtualDesktopAccessor[15 of 63]: 140726968844288
hwnd[0 of 0]:  
IsWindowOnDesktopNumberProc[15 of 63]: 140726968850016
MoveWindowToDesktopNumberProc[15 of 63]: 140726968850368
numdesktops[1 of 3]: 0
numwins[1 of 3]: 0
Ptr[0 of 0]:  
result[0 of 0]:  
Str[0 of 0]:  
UInt[0 of 0]:  
word_array[0 of 0]:  
```

How can I try to understand what is going on?

**Comment by Ciantic** [comment]
@stanstrup what is your exact AHK script? Note that AHK is flaming piece of shit that fails without error messages if you have a typo etc.

**Comment by stanstrup** [comment]
Thanks for looking into it.

```
DetectHiddenWindows Off
SetTitleMatchMode, 2

FILENAME = C:\Users\tmh331\Desktop\fix_windows\possaves.txt

hVirtualDesktopAccessor := DllCall("LoadLibrary", Str, "VirtualDesktopAccessor.dll", "Ptr") 
MoveWindowToDesktopNumberProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "MoveWindowToDesktopNumber", "Ptr")
IsWindowOnDesktopNumberProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "IsWindowOnDesktopNumber", "Ptr")

global numdesktops := GetDesktopsNumber()

F11::  ; Write list of "desktop@title"
EnumAddress := RegisterCallback("EnumWindowsProc", "Fast")
global numwins := 0
global file := FileOpen(FILENAME, "w")
DllCall("EnumWindows", "Ptr", EnumAddress, "Ptr", 0)
file.Close()
return

F12::  ; Read list and execute
global result
Loop, Read, %FILENAME%
{
    word_array := StrSplit(A_LoopReadLine, "@",, 2)  ; Omits periods.
    hwnd := WinExist(word_array[2])
    if (hwnd)
        DllCall(MoveWindowToDesktopNumberProc, UInt, hwnd, UInt, word_array[1] - 1)
}
return

GetDesktopsNumber()
{
    RegRead, cur, HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SessionInfo\1\VirtualDesktops, CurrentVirtualDesktop
    RegRead, alldesktops, HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VirtualDesktops, VirtualDesktopIDs
    return floor(strlen(alldesktops) / strlen(cur))
}

EnumWindowsProc(hwnd, lParam)
{
    WinGetTitle, title, ahk_id %hwnd%
    if title {
        desktopnum := GetHWNDDesktopNumber(hwnd)
        if (desktopnum >= 0) {
            numwins := numwins + 1
            line = % desktopnum "@" title "`r`n"
            file.Write(line)
        }
    }
    return true
}

GetHWNDDesktopNumber(hwnd)
{
  global  numdesktops, IsWindowOnDesktopNumberProc
  Loop, %numdesktops% {
    ix := A_Index - 1
    windowIsOnDesktop := DllCall(IsWindowOnDesktopNumberProc, UInt, hwnd, UInt, ix)
    if (windowIsOnDesktop == 1)
      return A_Index
  }
  return -1
}
```

**Comment by Ciantic** [comment]
What version of AHK you use? (The DLL does not care, it is tested with C code, but I can't understand the AHK code without knowing)

For instance there is new syntax I'm not aware, e.g. `global something := "value"`.

**Comment by stanstrup** [comment]
v1.1.31.01

**Comment by stanstrup** [comment]
Any news on this?

EDIT: see comments here: https://superuser.com/questions/1408214/make-programs-specifically-chrome-open-on-same-virtual-desktop#comment2304770_1477582
Somewhat working but I only get what is on the desktop I am on.

**Comment by Ciantic** [comment]
@stanstrup This works for me. 

Your script is weird btw, it uses some registry trick, even though the DLL exports functions directly getting desktop numbers `GetDesktopCount()`.

**Comment by Ciantic** [comment]
Secondly you should use `* int GetWindowDesktopNumber(HWND window)` instead of that last function
