### ISSUE TITLE
App icon starts flashing, gets added to other workspaces

### ISSUE THREAD

**Issue by c0ffeeartc** [Ciantic/VirtualDesktopAccessor#3]
On switching virtual desktops one of the program icons starts flashing, gets added to other workspaces, and unhides "auto-hidden" taskbar until icon gets clicked.

**Comment by Ciantic** [comment]
@c0ffeeartc this is a problem for Windows 10 desktops, if you quickly switch desktops it looses the plot sometimes. Unfortunately Microsoft probably doesn't care.

You can disable flashing taskbar buttons completly if you want, by in-memory patching explorer.exe: https://github.com/Ciantic/DisableFlashingTaskbarButtons

**Comment by c0ffeeartc** [comment]
Good read, I might be getting back at it to see how to solve things.

There is another issue https://github.com/Ciantic/VirtualDesktopAccessor/issues/4 , that I think might be related to this one
