### ISSUE TITLE
ErrorLevel  0xc0000005 from DLLCalls involving windows.

### ISSUE THREAD

**Issue by dowy** [Ciantic/VirtualDesktopAccessor#30]
The following DLLCalls always return ErrorLevel 0xc0000005:
- MoveWindowToDesktopNumberProc
- IsPinnedWindow
- PinWindow

This is running on Windows10 Enterprise, version 1709, Build 16299.1625
AutoHotKey Version v1.1.13.01

My AHK code is:
```
IsPinnedWindowProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "IsPinnedWindow", "Ptr")
WinGet, activeHwnd, ID, A
isPinned := DllCall(IsPinnedWindowProc, UInt, activeHwnd)
```
Other calls not involving a window, such as GoToDesktopNumber work fine.
I am using three monitors in case that is significant.

I do not have admin access to my PC and a number of permissions may well be locked down by policy.

Do you know what the problem might be and how I can fix it?

**Comment by Ciantic** [comment]
Windows build 1709 does *not* work with the latest DLL. You have to dig 1709 build from the history unfortunately.
