### ISSUE TITLE
VWMess Is not called anymore

### ISSUE THREAD

**Issue by ghost** [Ciantic/VirtualDesktopAccessor#31]
After updating windows on my PC VWMess callback which is supposed to be called on desktop change is not called anymore.

**Comment by Ciantic** [comment]
@Trismegistos84 updated to what? The Lates DLL is known to work with currently latest Windows 1903 (Build 10.0.18363). 

I haven't tested or installed yet unreleased 20H1.

**Comment by ghost** [comment]
I have updated to Windows 1903. Code from GitHub did not work but I may have one of the older dll files -- which used to work with older Windows 10.

**Comment by Ciantic** [comment]
Yea, you need to download the latest DLL from here:  https://github.com/Ciantic/VirtualDesktopAccessor/raw/master/x64/Release/VirtualDesktopAccessor.dll It works with 1903

**Comment by ghost** [comment]
I have checked the dll you provided and I can confirm it works.
