### ISSUE TITLE
Rust: last virtual desktop is not listed in `get_desktops()` output

### ISSUE THREAD

**Issue by slavoutich** [Ciantic/VirtualDesktopAccessor#35]
I suspect it happens because [here](https://github.com/Ciantic/VirtualDesktopAccessor/blob/5d025d774c07a3d8fdc43bd1d26dd5d72bb5dacc/src/service.rs#L99) the range is `0..(count-1)` instead of `0..count`.

I checked in [my fork](https://github.com/slavoutich/VirtualDesktopAccessor/tree/fix_virtual_desktops_listing) that I get four desktops if I fix it, but now I have `DesktopNotFound` if I try to get its name, planning to dig into it later.

System: Windows 10 Pro 20H2, build number 19042.685.

**Comment by Ciantic** [comment]
Yes, merged.
