### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by adrian88888888** [Ciantic/VirtualDesktopAccessor#39]
How I transform this into a DllCall in ahk?:
```
* uint ViewGetByLastActivationOrder(HWND *windows, UINT count, BOOL onlySwitcherWindows, BOOL onlyCurrentDesktop) // Get windows in alt tab order
```
My best guess is:
```autohotkey
ViewGetByLastActivationOrder(){
	return DllCall(ViewGetByLastActivationOrderProc, Int, what goes here?,UINT, what goes here?,BOOL, what is this for?,BOOL,1)
}
```
Sorry, im new to github and i don't know where to ask

**Comment by Ciantic** [comment]
I actually never envisioned to use those from AutoHotkey (it's a terrible language for that) but you should be able to pass in a raw zeroed UINT, and when you get it back it contains an pointer to C array with length you give in second argument as count.

Why do you want to call that function? It's more of an experiment at this point, and pretty much unrelated to main functions.

**Comment by adrian88888888** [comment]
I wanted to get the list of alt+tab windows, and I had 2 choices:
1. use a callback to that function in the .dll
2. use a long function that someone made in ahk in a forum(but works)

I don't understand C, I don't know what a raw zeroed UINT is, im newbie, and you say that is more of an experimental thing, so I go with option number 2

I don't know if I close this, or you do, I don't know how github works yet
This is solved then, thankssss, I reeeeally love your .dll btw, it's amazing!!!!
