### ISSUE TITLE
How to use the Thumbnail HWND?

### ISSUE THREAD

**Issue by Wzzzx** [Ciantic/VirtualDesktopAccessor#44]
I wanna save the thumbnail with a PNG picture, If I use the `ViewGetThumbnailHwnd` to get the view of one Window, how to save the thumbnail?

**Comment by Ciantic** [comment]
I have no idea, I don't think my library is suitable for those though. I managed to replicate the live previews using those ThumbnailHwnd's but I don't know how to get image thumbnails.

Besides, I plan to remove those View* functions, they are not useful in the virtual desktops.
