### ISSUE TITLE
Can it be update for windows 11?

### ISSUE THREAD

**Issue by Yusuf007R** [Ciantic/VirtualDesktopAccessor#45]
I Really like to mess around with this dll, sadly is broken on windows 11.

**Comment by itzjakm** [comment]
Check this repo: https://github.com/skottmckay/VirtualDesktopAccessor

**Comment by suskozaver** [comment]
did anyone get it to work? i had win + 1, 2, 3, 4  to switch desktops, but even with this DLL it doesn't work for me...

**Comment by Yusuf007R** [comment]
it does work for me, except that I use alt key not win, maybe they change something about win key on win11

**Comment by suskozaver** [comment]
Works for me also now! After i changed to Alt it also didn't work. 
(re)installed Microsoft Visual C++ Redistributable 2015-2019 and now it works. 

thx for the help!

**Comment by Ciantic** [comment]
Huh? What does ALT key has anything to do with this? This is a DLL that is agnostic on keys... if Windows key doesn't work it's a problem in AutoHotkey.

**Comment by Yusuf007R** [comment]
We do know is has nothing to do with this DLL, I'm sorry for discussing that here.

**Comment by Ciantic** [comment]
Okay, if it works with Windows 11, I'll close this, thanks!
