### ISSUE TITLE
Feature Request - Support for Win 11

### ISSUE THREAD

**Issue by PaulSorauer-IPG** [Ciantic/VirtualDesktopAccessor#46]
Hi there

I've been using VirtualDesktopAccessor.dll via 
[win-10-virtual-desktop-enhancer](https://github.com/sdias/win-10-virtual-desktop-enhancer) for years, but unfortunately the AutoHotKey scripts no longer appear to be working on Windows 11.

I'm wondering what's required to rebuild the dll for Win 11? I would offer to assist but I'm a pure C# not C++ guy.

Thanks,

Paul

**Comment by pukkandan** [comment]
According to https://github.com/Ciantic/VirtualDesktopAccessor/issues/45, it works and only AHK's keybindings are broken

**Comment by Ciantic** [comment]
That's right, the problem is with AHK and Windows-key if I'm not mistaken.

**Comment by PaulSorauer-IPG** [comment]
Thanks. I was messing around with the AHK scripts but couldn't get it working. At least I've a direction to investigate properly now. 😊
