### ISSUE TITLE
createVirtualDesktop, removeVirtualDesktop

### ISSUE THREAD

**Issue by huo-feng-ding** [Ciantic/VirtualDesktopAccessor#48]
Can you add createVirtualDesktop, removeVirtualDesktop these two functions

**Comment by Ciantic** [comment]
yeah, they are on the Rust branch, I haven't just had time to remove this C++ part and replace the DLL with Rust version.

**Comment by Ciantic** [comment]
*🎶TIDLINGTIDLINGTIDLING🎵* 
TWO YEARS LATER

It's now implemented, but for only to Windows 11 version of this binary: https://github.com/Ciantic/VirtualDesktopAccessor/releases
