### ISSUE TITLE
Win 11 issues

### ISSUE THREAD

**Issue by loggerheads-with-binary** [Ciantic/VirtualDesktopAccessor#49]
The functions from the DLL, namely: 

```
IsWindowOnCurrentVirtualDesktopProc  
GetCurrentDesktopNumberProc
GoToDesktopNumberProc  
MoveWindowToDesktopNumberProc
```

seem to not be working properly. Sometimes there are erratic window movements, but mostly nothing. Can this be fixed(on my end,  by the signature or recompilation after some edits) or is this some Windows issue or will the program have to be redeveloped?

**Comment by Ciantic** [comment]
Others seems to report the DLL works on Windows 11 though... I don't have W11.

**Comment by loggerheads-with-binary** [comment]
Ohh, okay. I'll just check if it's a build issue or something. Thank you
