### ISSUE TITLE
Flashing windows in taskbar

### ISSUE THREAD

**Issue by lewisd32** [Ciantic/VirtualDesktopAccessor#5]
First off, thanks for an awesome tool! I love being able to set up win-Fkeys to switch to specific desktops.

I've noticed some weird behaviour though.  When I rapidly cycle between a few desktops using these hotkeys, often whichever window was focused on one of those desktops ends up in the taskbar, flashing like it does normally to indicate some activity.  This doesn't happen when using the built-in ctrl-win-left/right keys for switching. In fact, switching through all the desktops using those keys clears the flashing windows.

Testing in more detail, it seems what's happening is that when switching to a desktop (using VirtualDesktopAccessor), the window that's focused on that desktop starts flashing in the taskbar sometimes. I can't seem to figure out why it only happens sometimes.

**Comment by Ciantic** [comment]
That flashing bug has nothing to do with this DLL, see #3 - it's bug in the Windows Explorer, and yes it also happens with ctrl+win+left sometimes. And it happens with other programs that uses Windows API calls to change desktop.

I even made a explorer.exe in memory patch to prevent whole flashing taskbar button: 

https://github.com/Ciantic/DisableFlashingTaskbarButtons
http://ciantic.blogspot.fi/2015/10/in-memory-patching-explorerexe-to.html

**Comment by Ciantic** [comment]
If someone else is hit by this, very easy way to avoid this is to call:

```
    ; Try to avoid flashing task bar buttons
    WinActivate, ahk_class Shell_TrayWnd
```

Just before changing desktop.
