### ISSUE TITLE
DLL incompatible with Windows 11 (not AHK issue)

### ISSUE THREAD

**Issue by tdy** [Ciantic/VirtualDesktopAccessor#51]
I believe the previous Windows 11 threads (#45, #46, #49) have misdiagnosed the problem. In my testing, the cause is _not_ AHK.

**Using the exact same AHK script:**

* [skottmckay's DLL (c83a6f3)] **works** on Windows 11 21H2 (22000.434)
* [Ciantic's DLL (5bc1bba)] **does not work** on Windows 11 21H2 (22000.434)

I don't know the API, but it seems the key fixes occurred in [skottmckay/545882e] since the previous DLLs do not work and the subsequent ones do.

Maybe @skottmckay can provide some insight (or possibly submit a PR upstream here).

  [skottmckay's DLL (c83a6f3)]: https://github.com/skottmckay/VirtualDesktopAccessor/blob/c83a6f3e06dad7360e8a41bb233c0c7ccf94e075/x64/Release/VirtualDesktopAccessor.dll
  [Ciantic's DLL (5bc1bba)]: https://github.com/Ciantic/VirtualDesktopAccessor/blob/5bc1bbaab247b5d72e70abc9432a15275fd2d229/x64/Release/VirtualDesktopAccessor.dll
  [skottmckay/545882e]: https://github.com/skottmckay/VirtualDesktopAccessor/commit/545882ede689967c7b65a8872f72deee22019ab3

**Comment by saturnspike** [comment]
Thanks for posting this, I can confirm skottmckay's DLL also works for me on Win 11 build 22000.

**Comment by felipecrp** [comment]
I tested the DLL with Windows 11 21H2 (22000.675) but it did not work. I tested the move app to another desktop.

**Comment by skottmckay** [comment]
Use the latest version with the latest Windows. 

https://github.com/skottmckay/VirtualDesktopAccessor/commit/a6e64d6ac40b907fe2a8bcf8fda8504ff8a6bcb1

**Comment by hklene** [comment]
21H2 (Build 220000, 1098) does nothing for me with [a6e64d6](https://github.com/skottmckay/VirtualDesktopAccessor/commit/a6e64d6ac40b907fe2a8bcf8fda8504ff8a6bcb1), but it works fine with previous [c83f683](https://github.com/skottmckay/VirtualDesktopAccessor/blob/c83a6f3e06dad7360e8a41bb233c0c7ccf94e075/x64/Release/VirtualDesktopAccessor.dll)

**Comment by Ciantic** [comment]
I'm installing Windows 11 in few weeks as I get new workstation.

If there is an issue, I will publish a new DLL.

**Comment by Ciantic** [comment]
https://github.com/Ciantic/VirtualDesktopAccessor/releases/tag/2023-01-12-windows11 here is the release, I use the release section for now

I'm still experiencing some crashes with my AHK script when using the OnChangeDesktop hook, I will investigate this, besides that it seems to be working.

**Comment by skottmckay** [comment]
> I'm still experiencing some crashes with my AHK script when using the OnChangeDesktop hook, I will investigate this, besides that it seems to be working.

FWIW I don't get crashes but it has been a long time since I edited the AHK script. Attached (with .txt added to filename to make github happy) in case it helps.
[virtual-desktop-enhancer.ahk.txt](https://github.com/Ciantic/VirtualDesktopAccessor/files/10398246/virtual-desktop-enhancer.ahk.txt)
