### ISSUE TITLE
Not working after machine refresh

### ISSUE THREAD

**Issue by gityta** [Ciantic/VirtualDesktopAccessor#52]
I have a company supplied laptop (HP) and had Virtual Desktop Enhancer running fine for over a year.  I left the company and they let me keep the laptop.  Easiest way to remove company software was to do a factory reset, which I did.  VDE hasn't worked since.  After a while, upgraded the machine to Win 11 so I could get familiar with it.  VDE still doesn't work.  Not sure what to try.  I've run VDE (using the exe) on multiple machines (including this one) for years without any trouble.  

It "loads" but never shows the desktop number on the systray icon, just the H.  No keyboard shortcuts work.  Not sure what to do.

Any thoughts on what may be keeping it from working or what I can try?  Any suggestions will be appreciated.

**Comment by Ciantic** [comment]
It's possible that it doesn't work with Windows 11 at the moment.

I'm still running Windows 10, but in few weeks I will be setting up a new workstation with Windows 11 on it.

**Comment by Ciantic** [comment]
This works now on Windows 11. Maybe that's what you are using?

New DLL version here: https://github.com/Ciantic/VirtualDesktopAccessor/releases/
