### ISSUE TITLE
Can it get the name of desktops?

### ISSUE THREAD

**Issue by ZhuangQu** [Ciantic/VirtualDesktopAccessor#55]
I have read the sample. We can only get the number, not the name. But the name is more important than the number.

**Comment by Ciantic** [comment]
I will fix that. It's implemented in my API, but not in the DLL, but I'm stuck with other problem at the moment:

I've been debugging for the past week very annoying race conditions with the OnChange hooks. If I swap virtual desktops 1000 times in a rapid fashion the DLL crashes.

**Comment by Ciantic** [comment]
@ZhuangQu now it can get and set desktop name, get a new DLL and and see the example:

New DLL here: https://github.com/Ciantic/VirtualDesktopAccessor/releases/
