### ISSUE TITLE
Crash when adding a desktop while listening events

### ISSUE THREAD

**Issue by Ciantic** [Ciantic/VirtualDesktopAccessor#56]

**Comment by ZhuangQu** [comment]
I also encounter this problem after pressing `Win+Tab` and clicking the `+` button.

**Comment by ZhuangQu** [comment]
After removing `OnChangeDesktop`, there is still 1% probability of crashing when operating in taskview. `OnChangeDesktop` increases the probability to 100%.

**Comment by ZhuangQu** [comment]
I have to call `UnregisterPostMessageHook` before adding a desktop, and call `RegisterPostMessageHook` after adding. This can avoid crash, but inconvenient.
```
SetTimer(check, 1)
check() {
    if WinActive("ahk_class XamlExplorerHostIslandWindow") {
        VBA_call("UnregisterPostMessageHook", "Uint", A_ScriptHwnd)
        WinWaitClose()
        VBA_call("RegisterPostMessageHook", "Uint", A_ScriptHwnd, "Uint", 0xFFFF)
    }
}
```

**Comment by ZhuangQu** [comment]
When we add a desktop, we will jump to it automatically. When we jump to a new desktop, it may still "does not exist" and has not yet been initialized. I guess this is the reason for carsh.

**Comment by Ciantic** [comment]
Wow, thanks, I will try to experiment with that.

I have some crazy tests in my code, like changing desktop ~1000 times as rapidly as possible, and they encounter crashes sometimes too when I have listener enabled. (Even though I'm not adding or removing desktops.)

I don't like that it may crash.

**Comment by Ciantic** [comment]
I think, can't be sure, I've figured this. 

If I use `CoInitializeEx` with `COINIT_APARTMENTTHREADED` it works, but e.g. with `COINIT_MULTITHREADED` it fails or with just `CoIncrementMTAUsage` it fails.

I have written a lot of garbage threading tests to figure this one out, with `COINIT_APARTMENTTHREADED` it doesn't crash. I don't get these apartments.

**Comment by Ciantic** [comment]
Now this shouldn't crash when adding desktops.
