### ISSUE TITLE
Sometimes Crash with 0xC0000005

### ISSUE THREAD

**Issue by ZhuangQu** [Ciantic/VirtualDesktopAccessor#57]
My system is Windows 11. I wrote an AutoHotkey script which executes `GetDesktopCount`, `GetCurrentDesktopNumber` and `GetDesktopName` for 16 consecutive times every 100 ms. After running for about 1 hour, AutoHotkey crashes with `0xC0000005` and then loses response.

**Comment by Ciantic** [comment]
Why are you calling it every 100ms for an hour? There is event listener which triggers when you change desktop.

I've even gotten explorer.exe to crash if I call some of the functions too many times, something goes wrong somewhere.

**Comment by ZhuangQu** [comment]
I call the DLL so frequently to know whether the desktop has changed. The listener will crash when I add a desktop in taskview, so I dare not use it.

**Comment by ZhuangQu** [comment]
I add
```
ProcessSetPriority("Realtime")
```
to my AutoHotkey script and it doesn't crash anymore. I don't know why so.

**Comment by ZhuangQu** [comment]
I add
```
ProcessSetPriority("Realtime")
```
to my AutoHotkey script and it doesn't crash anymore. I don't know why so.

**Comment by Ciantic** [comment]
Do you add and remove a lot of desktops every day?

Listener is a way to go here, but I do need to find the crash and fix it.

I have 16 desktops at all times, I don't add and remove these practically ever so it's a rare occasion for me.

**Comment by ZhuangQu** [comment]
Yes! And I found that raising the process priority can solve the problem, so I close it.
