### ISSUE TITLE
Didn't work for me

### ISSUE THREAD

**Issue by hzzm** [Ciantic/VirtualDesktopAccessor#6]
Unfortunately i couldn't make it work. The main feature I'm looking for is "Switch to Desktop #".

I chose simple paths like C:\ahk\VirtualDesktopAccessor.dll
ran the compiled .exe as admin,
removed the parts with the background pictures,
changed the hotkeys to all kinds of different modifier combinations + a number.

This is my .ahk at the moment: http://dpaste.com/2V0QWQE , both files reside in C:\ahk\.
Latest Windows10 version with all updates and patches applied.

**Comment by Ciantic** [comment]
Did you install these: https://www.microsoft.com/en-us/download/details.aspx?id=48145 ?

**Comment by Ciantic** [comment]
Also you probably can just use this: 


```

hVirtualDesktopAccessor := DllCall("LoadLibrary", "Str", "C:\ahk\VirtualDesktopAccessor.dll", "Ptr") 
GoToDesktopNumberProc := DllCall("GetProcAddress", Ptr, hVirtualDesktopAccessor, AStr, "GoToDesktopNumber", "Ptr")

; Win + Ctrl + 1 = Switch to desktop 1
^!+1::DllCall(GoToDesktopNumberProc, Int, 0)

; Win + Ctrl + 2 = Switch to desktop 2
^!+2::DllCall(GoToDesktopNumberProc, Int, 1)

```

I you don't care about the event function

**Comment by Ciantic** [comment]
Oh yeah, and win+ctrl+1 is probably `^#1::DllCall...`

**Comment by hzzm** [comment]
Yes, i did download the VC++ redistributables as recommended in your readme.
Even with your most reduced script here, it still doesn't work. I used ^!+1.. for Ctrl+Alt+Shift+1.. intentionally to eliminate shortcut conflicts as possible failure reason.

I tried using MsgBox to tell me whether or not the Dll was successfully included, but i couldn't nail down AHK's syntax for that.

**Comment by Ciantic** [comment]
```
hVirtualDesktopAccessor := DllCall("LoadLibrary", "Str", "C:\Source\CandCPP\VirtualDesktopAccessor\x64\Release\VirtualDesktopAccessor.dll", "Ptr") 
WinErrorcode := DllCall("GetLastError")
MsgBox, `Windows' errorcode is %WinErrorcode%
```

Should give 0 on each (no error).

Reference codes from here: https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

**Comment by Ciantic** [comment]
In Issue #1 I gave a bunch of ways to debug, in the end it was the redistributables, but you might want to look at the other ways I asked to test. E.g. invisible chars (utf8 chars) in the editor.

**Comment by hzzm** [comment]
Thanks for your help, i'll close this.
I gave up and went with one of these 3rd-party virtual desktop environments.
