### ISSUE TITLE
DLL file always returning zero

### ISSUE THREAD

**Issue by mwenku** [Ciantic/VirtualDesktopAccessor#63]
# DLL file always returning zero

I have been trying to use the dll to get the current desktop name, but always getting a 0. i tried calling the function from python but was getting the same result. is the file only supported in rust?

![image](https://github.com/Ciantic/VirtualDesktopAccessor/assets/64831126/16d9fb44-d064-4e3c-987a-14015763ee41)

**Comment by Ciantic** [comment]
Hmm, GetName works from AutoHotkey

**Comment by mwenku** [comment]
> Hmm, GetName works from AutoHotkey

I'll try it in rust instead
