### ISSUE TITLE
Error: Call to nonexistent function

### ISSUE THREAD

**Issue by la4zen** [Ciantic/VirtualDesktopAccessor#64]
DllCall(RegisterPostMessageHookProc, "Ptr", A_ScriptHwnd, "Int", 0x1400 + 30, "Int")
Windows 11 Pro | AHK 2
This line exists in example.

**Comment by la4zen** [comment]
5 line in example, change path worked to me. Sorry!

**Comment by xav-ie** [comment]
wait, how did you fix this? sorry! AHK is very new to me. @la4zen

**Comment by Yunuuuu** [comment]
The same problem but exist event the right DLL PATH
