### ISSUE TITLE
is Windows 10 still supported with the crate?

### ISSUE THREAD

**Issue by maxomatic458** [Ciantic/VirtualDesktopAccessor#65]
I am on Windows 10 Home 22H2 19045.3086
and ``get_desktop_count()`` returns this for me: ``ComError(HRESULT(0x80004002))``.

this does work with version 0.20 for me, but there i experience this panic when spam-switching virtual desktops: 

thread '<unnamed>' panicked at 'Underflow of reference count', ``C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winvd-0.0.20\src\changelistener.rs:92:1``

**Comment by Ciantic** [comment]
Windows 10 is not supported in the Rust crate, some old versions might work as you have figured out already.

**Comment by maxomatic458** [comment]
Ok good to know

I also fixed my problem with 0.20, I added a min delay of 50ms between each call of ``get_desktop_count`` and that fixed the panic.
