### ISSUE TITLE
Build 22631.2050

### ISSUE THREAD

**Issue by itzjakm** [Ciantic/VirtualDesktopAccessor#66]
In Windows 11 Insider Preview Build 22631.2050 (KB5028256) the DLL stopped working, I'm trying to fix it but I'm stuck.
I downloaded https://github.com/widavies/GetVirtualDesktopAPI_DIA and got the log:

`IID_IVirtualDesktopManager: A5CD92FF-29BE-454C-8D04-D82879FB3F1B
IID_IVirtualDesktopAccessibility: 9975B71D-0A84-4909-BDDE-B455BBFA55C6
IID_IVirtualDesktop: 3F07F4BE-B107-441A-AF0F-39D82529072C
IID_IVirtualDesktopManagerInternal: 4970BA3D-FD4E-4647-BEA3-D89076EF4B9C
IID_IVirtualDesktop2: A871910E-6CC0-4E65-8B9B-458CE9115E30
IID_IVirtualDesktopHotkeyHandler: 44B664EC-253C-4F5C-827B-78FB573756AE
IID_IVirtualDesktopSwitcherHost: 1BE71764-E771-4442-B78F-EDA2C7F067F3
IID_IVirtualDesktopAnimationSyncNotificationService: 0DDAF2D8-C38F-4638-95FC-FB9C6DDAE52F
IID_IVirtualDesktopNotification: B287FA1C-7771-471A-A2DF-9B6B21F0D675
IID_IVirtualDesktopPinnedApps: 4CE81583-1E4C-4632-A621-07A53543148F
IID_IVirtualDesktopNotificationService: 0CD45E71-D927-4F15-8B0A-8FEF525337BF
IID_IVirtualDesktopSwitcherInvoker: 7A25165A-86F1-4B4A-B1D2-E89650CD9589
IID_IVirtualDesktopTabletModePolicyService: 56B32065-0BB3-42E2-975D-A559DE1316E8
IID_IVirtualDesktopAnimationSyncNotification: 6CAFD3F1-05D1-4D26-A32A-9907A72C920B
IID_IVirtualDesktopManagerInternal2: A3175F2D-239C-4BD2-8AA0-EEBA8B0B138E

Dumping vftable: const CVirtualDesktopManager::`vftable'{for `Microsoft::WRL::Details::ImplementsHelper<struct Microsoft::WRL::RuntimeClassFlags<3>,1,struct Microsoft::WRL::Details::ImplementsMarker<class Microsoft::WRL::FtmBase> >'}
    Method  0: [thunk]:public: virtual long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<3>,1,1,0,struct Microsoft::WRL::ChainInterfaces<struct IVirtualDesktopManagerPrivate,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil>,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,struct ISuspendableVirtualDesktopManager,struct IImmersiveWindowMessageNotification,class Microsoft::WRL::FtmBase>::QueryInterface`adjustor{56}' (struct _GUID const & __ptr64,void * __ptr64 * __ptr64) __ptr64 (?QueryInterface@?$RuntimeClassImpl@U?$RuntimeClassFlags@$02@WRL@Microsoft@@$00$00$0A@U?$ChainInterfaces@UIVirtualDesktopManagerPrivate@@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@VNil@Details@WRL@Microsoft@@V4567@V4567@V4567@V4567@V4567@V4567@@23@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@UISuspendableVirtualDesktopManager@@UIImmersiveWindowMessageNotification@@VFtmBase@23@@Details@WRL@Microsoft@@WDI@EAAJAEBU_GUID@@PEAPEAX@Z)
    Method  1: [thunk]:public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<3>,1,1,0,struct Microsoft::WRL::ChainInterfaces<struct IVirtualDesktopManagerPrivate,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil>,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,struct ISuspendableVirtualDesktopManager,struct IImmersiveWindowMessageNotification,class Microsoft::WRL::FtmBase>::AddRef`adjustor{56}' (void) __ptr64 (?AddRef@?$RuntimeClassImpl@U?$RuntimeClassFlags@$02@WRL@Microsoft@@$00$00$0A@U?$ChainInterfaces@UIVirtualDesktopManagerPrivate@@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@VNil@Details@WRL@Microsoft@@V4567@V4567@V4567@V4567@V4567@V4567@@23@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@UISuspendableVirtualDesktopManager@@UIImmersiveWindowMessageNotification@@VFtmBase@23@@Details@WRL@Microsoft@@WDI@EAAKXZ)
    Method  2: [thunk]:public: virtual unsigned long __cdecl Microsoft::WRL::Details::RuntimeClassImpl<struct Microsoft::WRL::RuntimeClassFlags<3>,1,1,0,struct Microsoft::WRL::ChainInterfaces<struct IVirtualDesktopManagerPrivate,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil,class Microsoft::WRL::Details::Nil>,struct IVirtualDesktopManagerInternal,struct IVirtualDesktopManagerInternal2,struct ISuspendableVirtualDesktopManager,struct IImmersiveWindowMessageNotification,class Microsoft::WRL::FtmBase>::Release`adjustor{56}' (void) __ptr64 (?Release@?$RuntimeClassImpl@U?$RuntimeClassFlags@$02@WRL@Microsoft@@$00$00$0A@U?$ChainInterfaces@UIVirtualDesktopManagerPrivate@@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@VNil@Details@WRL@Microsoft@@V4567@V4567@V4567@V4567@V4567@V4567@@23@UIVirtualDesktopManagerInternal@@UIVirtualDesktopManagerInternal2@@UISuspendableVirtualDesktopManager@@UIImmersiveWindowMessageNotification@@VFtmBase@23@@Details@WRL@Microsoft@@WDI@EAAKXZ)
    Method  3: public: virtual long __cdecl Microsoft::WRL::FtmBase::GetUnmarshalClass(struct _GUID const & __ptr64,void * __ptr64,unsigned long,void * __ptr64,unsigned long,struct _GUID * __ptr64) __ptr64 (?GetUnmarshalClass@FtmBase@WRL@Microsoft@@UEAAJAEBU_GUID@@PEAXK1KPEAU4@@Z)` 
(And much more...)
But I don't understand any of this.
If someone could tell me how can I change the rust code to reflect this (or if there is another way to fix it) I would highly appreciate.

**Comment by ondras** [comment]
Having (probably) the same issue. The build `22631.2115` does not seem to work with the current DLL (nor any of the older DLLs that I have stored for reference).

**Comment by itzjakm** [comment]
check out this [itzjakm/VirtualDesktopAccessor](https://github.com/itzjakm/VirtualDesktopAccessor/tree/Build-22631). The DLL is available in the releases.

**Comment by ondras** [comment]
> check out this [itzjakm/VirtualDesktopAccessor](https://github.com/itzjakm/VirtualDesktopAccessor/tree/Build-22631). The DLL is available in the releases.

Works, thanks a lot!

One feature is not working for me - the "on desktop change" notification/callback. But that might be some AHK-related incompatibility in my code. Will debug this a bit more and let you know.

**Comment by itzjakm** [comment]
I had the same problem and was solved like this:
In my ahk code there was something like this
`DllCall(RegisterPostMessageHookProc, "Ptr", hwnd, "Int", 0x1400 + 30, "Int")`
And I had to change the word hwnd for A_ScriptHwnd.
So like this in the end:
`DllCall(RegisterPostMessageHookProc, "Ptr", A_ScriptHwnd, "Int", 0x1400 + 30, "Int")`

**Comment by ondras** [comment]
Yeah, just changed the code exactly as you did - it works now 👍
