### ISSUE TITLE
switching to an uneditable window

### ISSUE THREAD

**Issue by MichaRotstein** [Ciantic/VirtualDesktopAccessor#69]
Here is the scenario:
- switch to VD2 and focus on a window that can not receive text input ie VLC
- go back to VD1 and click in an editable window ie Notepad
- switch to VD2 (ie VLC) and start typing ie xxx
- switch back to VD1 you will see the text (xxx) in notepad ! 

This issue makes virtual desktops very annoying in heavy use, seems to be a windows bug, is there a way around it using this dll and AHK ?

**Comment by Ciantic** [comment]
You can save the active window by desktop, and when switching desktop and activate the window. It should be doable with AHK.

**Comment by MichaRotstein** [comment]
Thanks @Ciantic ! Sorry for late reply

My issue is the dll only provides RegisterPostMessageHookProc at which point I can no longer ask AHK for the currently activated window to save it !

Is there a way to get a hook _before_ the VD changes ?
Or any other idea ?

**Comment by MichaRotstein** [comment]
I did manage to solve this:

```
VDA_PATH := A_ScriptDir . "\VirtualDesktopAccessor.dll"
hVirtualDesktopAccessor := DllCall("LoadLibrary", "Str", VDA_PATH, "Ptr")
GetCurrentDesktopNumberProc := DllCall("GetProcAddress", "Ptr", hVirtualDesktopAccessor, "AStr", "GetCurrentDesktopNumber", "Ptr")
GoToDesktopNumberProc := DllCall("GetProcAddress", "Ptr", hVirtualDesktopAccessor, "AStr", "GoToDesktopNumber", "Ptr")
hWnd := Map()
capslock:: {
  current := DllCall(GetCurrentDesktopNumberProc, "Int")
  hWnd[current] := WinActive('A')
  next:= current = 0 ? 1 : 0
  DllCall(GoToDesktopNumberProc, "Int", next, "Int")
  Try WinActivate hWnd[next]
}
```
