### ISSUE TITLE
Anniversary Update issue

### ISSUE THREAD

**Issue by AydemRagha** [Ciantic/VirtualDesktopAccessor#7]
Hi there, I fear that the upcoming Anniversary Update will break permanently your current DLL version.
It stopped working more or less since insider preview 14295. I've awaited 'cause there were chances it started working again in subsequently releases, but that's not the case.
So I thought pointing you out the fact.
I'm not a techie but likely some changes in the API occured because some other tools I'm using, which take advantage of IVirtualDesktopManager interface, broke out with insiders previews for 3 months circa.

Some issue reportings below (maybe you are already aware of those):

https://github.com/Eun/MoveToDesktop/issues/9

https://github.com/Grabacr07/VirtualDesktop/issues/9

Here there is no issue reported but I grant you is not getting the virtual desktop as it should: https://github.com/m0ngr31/VirtualDesktopManager

Also I think your DLL is hugely underrated (and probably just unknown by too much people):
I've written an AutoHotKey script that allow me to use only the functions provided by your code to achieve all the results, and even better, of the tools above mentioned.
So I can completely stay without them.
You'll realize I'm very worried about 2nd August Windows 10 update!!! :-)

IMHO my script plus VirtualDesktopAccessor.dll is far smoother, convenient and, more than everything, lighter than any other 3rd party software (e.g. the renowned “Dexpot”) at least in Windows 10.

This guy have done a pretty good study on IvirtualDesktopManager,
http://www.cyberforum.ru/blogs/105416/blog3671.html
and maybe you could contact him once Anniversary Update will be released.

If you want I can share my script with you to have a look at it. 

Greetings and thanks for your endeavours in creating this utility.
Thanks for your attenction.

**Comment by Ciantic** [comment]
Hello, thanks for the investigation.

I don't run insider versions at the moment so I can't try to fix it yet.

From this: https://github.com/Grabacr07/VirtualDesktop/issues/9 I can tell that probably Microsoft has changed the ID's. So fix is probably to find out the new numbers for these lines:

https://github.com/Ciantic/VirtualDesktopAccessor/blob/2964408cf86c78d946556424ff4a653c38ed011d/VirtualDesktopAccessor/Win10Desktops.h#L11-L15

Since IVirtualDesktopManagerInternal API is internal, their CLSID and IID have probably changed. This is just guess, but I suspect so.

**Comment by AydemRagha** [comment]
Ok, I got you. Really glad to hear you already have some clues and assumption about where to look and how to proceed for a fix. So we'll wait time after 2nd August release and see...

Thanks for your answer, bye

**Comment by Ciantic** [comment]
@AydemRagha I found a fix from the issue you posted. For now, until it's released there is two DLLs: 

https://github.com/Ciantic/VirtualDesktopAccessor/tree/master/x64/Release the 2016-07-22.dll works for latest Insider version, and presumably for Anniversary edition.

**Comment by AydemRagha** [comment]
What a promptness, great! I've just tried the new DLL and it's working flawlessly.
Many thanks!
I'm planning to open a topic on AHK forum to evangelize VirtualDesktopAccessor and release my script (it's nothing special but can be useful to some people) if you agree.
Bye

**Comment by VarunAgw** [comment]
Thanks :)
