### ISSUE TITLE
No Actions on Windows Build 22631.2191

### ISSUE THREAD

**Issue by MrYutz** [Ciantic/VirtualDesktopAccessor#70]
I am running 22631.2191.  I don't get any actions from the example script.

The hot keys are being triggered and appear to be calling the correct functions as a result, but there is no feedback or actions.

Any direction on troubleshooting the DLL or AHK?

```
135: MoveOrGotoDesktopNumber(1)
070: If (GetKeyState("LButton"))
073: GoToDesktopNumber(num)
065: DllCall(GoToDesktopNumberProc, "Int", num, "Int") (0.02)
066: Return
074: }
075: Return
135: } (0.64)
134: MoveOrGotoDesktopNumber(0)
070: If (GetKeyState("LButton"))
073: GoToDesktopNumber(num)
065: DllCall(GoToDesktopNumberProc, "Int", num, "Int")
066: Return
074: }
075: Return
134: } (0.75)
137: MoveOrGotoDesktopNumber(3)
070: If (GetKeyState("LButton"))
073: GoToDesktopNumber(num)
065: DllCall(GoToDesktopNumberProc, "Int", num, "Int")
066: Return
074: }
075: Return
137: } (12.30)
134: MoveOrGotoDesktopNumber(0)
070: If (GetKeyState("LButton"))
073: GoToDesktopNumber(num)
065: DllCall(GoToDesktopNumberProc, "Int", num, "Int")
066: Return
074: }
075: Return
```

**Comment by fredless** [comment]
I also see this problem. 

The virtual desktop enhancements in [Windows 23H2 Insider update](https://blogs.windows.com/windows-insider/2023/07/21/announcing-windows-11-insider-preview-build-22621-2050-and-22631-2050/) seem to break a lot of programs that would switch virtual desktops. Also reported a similar problem with SylphyHornPlus: https://github.com/hwtnb/SylphyHornPlusWin11/issues/33

**Comment by itzjakm** [comment]
Please see [here](https://github.com/Ciantic/VirtualDesktopAccessor/pull/68) for the updated dll and rust code. (You can find the dll in the [releases](https://github.com/itzjakm/VirtualDesktopAccessor/releases/tag/2023-08-01-windows11))

**Comment by MrYutz** [comment]
I can confirm that his fixed the issue.  Desktop switching works now.  Thank you @itzjakm!!
