### ISSUE TITLE
each call returns -1 after updating KB5029351

### ISSUE THREAD

**Issue by ZhuangQu** [Ciantic/VirtualDesktopAccessor#71]
After updating [KB5029351](https://support.microsoft.com/en-us/topic/august-22-2023-kb5029351-os-build-22621-2215-preview-9af25662-083a-43f5-b3a7-975fe25cc692), each VDA call returns `-1` and VDA doesn't work.

**Comment by SSue2** [comment]
+1

I am having the same issue after that particular update.

**Comment by SSue2** [comment]
Please see this closed issue -> the solution solved the problem for me:
https://github.com/Ciantic/VirtualDesktopAccessor/issues/70
