### ISSUE TITLE
KB5030219 breaks VirtualDesktopAccessor 

### ISSUE THREAD

**Issue by kofifus** [Ciantic/VirtualDesktopAccessor#73]
Sadly GetCurrentDesktopNumberProc and GoToDesktopNumberProc stopped working for me after 2023-09 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5030219)

**Comment by ericreeves** [comment]
The latest release from the rust branch fixes this.

**Comment by kofifus** [comment]
Thanks! where can I get the dll ?

**Comment by kofifus** [comment]
Thanks the DLL here https://github.com/Ciantic/VirtualDesktopAccessor/releases/ solved it
