### ISSUE TITLE
After installing update КВ50З0219 moving around doesn't work

### ISSUE THREAD

**Issue by bedware** [Ciantic/VirtualDesktopAccessor#74]
Hi there!
Yesterday I installed updates on my laptop and went to sleep.
Today I surprisingly found that moving between Virtual Desktops using this library is not working anymore.

I rolled back this update and all started working as before:
Security Update for Microsoft Windows (КВ50З0219)

Could anyone please confirm that for me?

**Comment by ken-swe** [comment]
Hi! I am also getting this problem after the same update (КВ50З0219) where I can no longer switch between Virtual Desktops.

**Comment by joshebosh** [comment]
I'm having same issue... The DLL (or something) seems to have stopped working after КВ50З0219

Edition	Windows 11 Pro
Version	22H2
Installed on	‎7/‎14/‎2023
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by mickedefault** [comment]
Make sure that you use the [new release](https://github.com/Ciantic/VirtualDesktopAccessor/releases/tag/2023-08-31-windows11). When I updated to that it worked for me, even though КВ50З0219 is installed

**Comment by bedware** [comment]
> Make sure that you use the [new release](https://github.com/Ciantic/VirtualDesktopAccessor/releases/tag/2023-08-31-windows11). When I updated to that it worked for me, even though КВ50З0219 is installed

Thank you! I checked - that works.
