### ISSUE TITLE
Stopped working in 22621.2506

### ISSUE THREAD

**Issue by jeremythille** [Ciantic/VirtualDesktopAccessor#80]
I've updated Windows 11 yesterday to 22621.2506, and VirtualDesktopEnhancer stopped working. I can switch between virtual desktops manually though.
I believe a new VirtualDesktopAccessor.dll update should do the trick.
Cheers

**Comment by Rykarix** [comment]
+1

**Comment by Ciantic** [comment]
It's working for me without changes. That is my winver.exe

![image](https://github.com/Ciantic/VirtualDesktopAccessor/assets/64731/fcd9410f-d8fa-4a7d-aaf6-718776887829)

**Comment by jeremythille** [comment]
Ooooooh I just made it work!
I renamed `virtualDesktopAccessor.dll` to `virtual-desktop-accessor.dll` and now it works like before!
Thanks anyway, keep up the good work :)
