### ISSUE TITLE
23H2 22631.3085

### ISSUE THREAD

**Issue by Zoubi91** [Ciantic/VirtualDesktopAccessor#86]
Just installed this version of Win11 and it doesn't work anymore. Worked like a charm before (Win11 22631.3007). Now :
- GetCurrentDesktopNumber returns an error
- GoToDesktopNumber does'nt return an error but doesn't go to the requested desktop

**Comment by Trollwut** [comment]
Same problem here. Was introduced today with update `2024-01 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034204)` on 2024-01-24.

**Comment by Ciantic** [comment]
Yeah, I'm working on this.

**Comment by Trollwut** [comment]
Downloaded the new DLL and used it. It indeed works for me!

Thanks for the quick solution!

**Comment by Zoubi91** [comment]
Same here, new DLL works again. Thanks so much for your incredibly quick reaction.
