### ISSUE TITLE
How to properly use the IApplicationView SetCloak function?

### ISSUE THREAD

**Issue by wewewdwe** [Ciantic/VirtualDesktopAccessor#94]
Hello, do you mind sharing how you found/find the methods of the IApplicationView class?
I mean all these functions:
https://github.com/Ciantic/VirtualDesktopAccessor/blob/45d66e83f4a11523faa9f2073b5241867e2a60a0/src/comapi/interfaces.rs#L157

**Comment by Lej77** [comment]
They were likely found by reading the debug symbols for Windows DLL files, you might find more info at [Reverse engineering process · Issue #14 · Slion/VirtualDesktop](https://github.com/Slion/VirtualDesktop/issues/14)

**Comment by Ciantic** [comment]
@wewewdwe 

Most of those are available in Microsoft debug symbols.

For instance I have forked one excellent script: https://github.com/Ciantic/DumpVDIA to dump all the vftables related to virtual desktop classes.
